version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    container_name: f1-sqlite3-server
    image: f1-sqlite3-server
    develop:
      watch:
        - action: sync
          path: ./
          target: /